export type FestivalLanguage = 'en' | 'es';

type TranslationKey = keyof typeof messages.en;

const messages = {
  en: {
    map: 'Map', rankings: 'Rankings', tapas: 'Tapas', language: 'Language', star: 'star', stars: 'stars', signIn: 'Sign in', signedIn: 'Signed in', logOut: 'Log out', writeReview: 'Write review', saveReview: 'Save review', editReview: 'Edit review', yourReview: 'Your review', noReviewsYet: 'No reviews yet', reviewSaved: 'Review saved.', festivalVisitor: 'Festival visitor', showReviews: 'Show reviews', hideReviews: 'Hide reviews', chooseRatingFirst: 'Choose a star rating before saving a review.', festivalMap: 'Festival map', mapped: 'mapped', selectMarker: 'Select a marker to see the establishment, its tapas and current ratings.', participating: 'Participating', closedOrWithdrawn: 'Closed or withdrawn', noCoordinates: 'No establishment coordinates are available yet. All establishments remain in the list below.', locationUnavailable: 'Location unavailable', rotateMapLeft: 'Rotate map left', resetNorth: 'Reset north', rotateMapRight: 'Rotate map right',
    festivalInformation: 'Festival information', location: 'Location:', loading: 'Loading festival…', unableToLoad: 'Unable to load festival data:', noFestival: 'No published festival is available yet.', standardTapaPrice: 'Standard tapa price:', liveRankings: 'Live tapa rankings', rankingDescription: 'Ranking blends each average with the festival-wide average using a five-rating baseline, so one vote does not dominate.', rankingScore: 'Score:', ratings: 'ratings', goodExcellent: '4–5★',
    withdrawn: 'Withdrawn', closed: 'Closed', openingHours: 'Opening hours:', phone: 'Phone:', whatsapp: 'WhatsApp:', website: 'Website', facebook: 'Facebook', publicRating: 'Rating:', unrated: 'Unrated', rateThisTapa: 'Rate this tapa', chooseStars: 'Choose 1–5 stars, then', chooseRating: 'Choose a rating', signInToRate: 'sign in to submit your rating', yourRating: 'Your rating:', notRatedYet: 'Not rated yet', outOfFive: 'out of 5 stars', removeRating: 'Remove my rating', removeReview: 'Remove my review', ratingsMaintenanceNotice: 'Ratings are temporarily unavailable for maintenance. Existing ratings are still shown.', reviewsMaintenanceNotice: 'Reviews are temporarily unavailable for maintenance. Existing reviews are still visible.', unsavedReviewTitle: 'Unsaved review', unsavedReviewMessage: 'You have an unsaved review. Save it before moving on?', discardChanges: 'Discard changes', stayHere: 'Stay here', signInAtAdmin: 'Sign in at /admin to rate this tapa.', noPublishedTapas: 'No published tapas.', reviewTooLong: 'Reviews must be 60 characters or fewer.', wantToTry: 'Want to try', removeWantToTry: 'Remove from want to try', createAccount: 'Create account', email: 'Email', password: 'Password', passwordHint: 'At least 8 characters', signingIn: 'Signing in…', creatingAccount: 'Creating account…', accountCreatedSignedIn: 'Account created and signed in.', accountCreatedConfirm: 'Account created. Check your email to confirm your account, then sign in.', invalidEmail: 'Enter a valid email address.', invalidPassword: 'Password must be at least 8 characters.', continueWithGoogle: 'Continue with Google', orContinueWith: 'or continue with email', openDetails: 'Open details', closeDetails: 'Close details', rateThisBar: 'Rate this bar / Would you come here again?', barRating: 'Bar rating:', removeBarRating: 'Remove my bar rating', reportProblem: 'Report a problem', reportProblemTitle: 'Report a problem', contactEmailOptional: 'Email or contact (optional)', problemDescription: 'Describe the problem', sendReport: 'Open email report', reportHint: 'This opens your email app with festival context included.', sortBars: 'Sort bars', numeric: 'Numeric', alphabetical: 'Alphabetical', notReviewedYet: 'No stars yet', signInToSort: 'Sign in to sort by bars with no stars yet.',
  },
  es: {
    map: 'Mapa', rankings: 'Clasificación', tapas: 'Tapas', language: 'Idioma', star: 'estrella', stars: 'estrellas', signIn: 'Iniciar sesión', signedIn: 'Sesión iniciada', logOut: 'Cerrar sesión', writeReview: 'Escribe una reseña', saveReview: 'Guardar reseña', editReview: 'Editar reseña', yourReview: 'Tu reseña', noReviewsYet: 'Aún no hay reseñas', reviewSaved: 'Reseña guardada.', festivalVisitor: 'Visitante', showReviews: 'Mostrar reseñas', hideReviews: 'Ocultar reseñas', chooseRatingFirst: 'Elige una valoración antes de guardar una reseña.', festivalMap: 'Mapa del festival', mapped: 'en el mapa', selectMarker: 'Selecciona un marcador para ver el establecimiento, sus tapas y sus valoraciones actuales.', participating: 'Participante', closedOrWithdrawn: 'Cerrado o retirado', noCoordinates: 'Todavía no hay coordenadas disponibles. Todos los establecimientos siguen apareciendo en la lista.', locationUnavailable: 'Ubicación no disponible', rotateMapLeft: 'Girar mapa a la izquierda', resetNorth: 'Restablecer norte', rotateMapRight: 'Girar mapa a la derecha',
    festivalInformation: 'Información del festival', location: 'Ubicación:', loading: 'Cargando festival…', unableToLoad: 'No se han podido cargar los datos del festival:', noFestival: 'Todavía no hay ningún festival publicado.', standardTapaPrice: 'Precio estándar de la tapa:', liveRankings: 'Clasificación de tapas en directo', rankingDescription: 'La clasificación combina cada media con la media del festival usando una base de cinco valoraciones, para que un solo voto no domine.', rankingScore: 'Puntuación:', ratings: 'valoraciones', goodExcellent: '4–5★',
    withdrawn: 'Retirada', closed: 'Cerrado', openingHours: 'Horario:', phone: 'Teléfono:', whatsapp: 'WhatsApp:', website: 'Web', facebook: 'Facebook', publicRating: 'Valoración:', unrated: 'Sin valorar', rateThisTapa: 'Valora esta tapa', chooseStars: 'Elige de 1 a 5 estrellas y después', chooseRating: 'Elige una valoración', signInToRate: 'inicia sesión para enviar tu valoración', yourRating: 'Tu valoración:', notRatedYet: 'Aún sin valorar', outOfFive: 'de 5 estrellas', removeRating: 'Eliminar mi valoración', removeReview: 'Eliminar mi reseña', ratingsMaintenanceNotice: 'Las valoraciones no están disponibles temporalmente por mantenimiento. Las valoraciones existentes siguen visibles.', reviewsMaintenanceNotice: 'Las reseñas no están disponibles temporalmente por mantenimiento. Las reseñas existentes siguen visibles.', unsavedReviewTitle: 'Reseña sin guardar', unsavedReviewMessage: 'Tienes una reseña sin guardar. ¿Quieres guardarla antes de continuar?', discardChanges: 'Descartar cambios', stayHere: 'Quedarme aquí', signInAtAdmin: 'Inicia sesión en /admin para valorar esta tapa.', noPublishedTapas: 'No hay tapas publicadas.', reviewTooLong: 'Las reseñas deben tener 60 caracteres o menos.', wantToTry: 'Quiero probarla', removeWantToTry: 'Quitar de quiero probarla', createAccount: 'Crear cuenta', email: 'Correo electrónico', password: 'Contraseña', passwordHint: 'Al menos 8 caracteres', signingIn: 'Iniciando sesión…', creatingAccount: 'Creando cuenta…', accountCreatedSignedIn: 'Cuenta creada y sesión iniciada.', accountCreatedConfirm: 'Cuenta creada. Revisa tu correo para confirmar la cuenta y después inicia sesión.', invalidEmail: 'Introduce una dirección de correo válida.', invalidPassword: 'La contraseña debe tener al menos 8 caracteres.', continueWithGoogle: 'Continuar con Google', orContinueWith: 'o continuar con correo electrónico', openDetails: 'Abrir detalles', closeDetails: 'Cerrar detalles', rateThisBar: 'Valora este bar / ¿Volverías aquí?', barRating: 'Valoración del bar:', removeBarRating: 'Eliminar mi valoración del bar', reportProblem: 'Informar de un problema', reportProblemTitle: 'Informar de un problema', contactEmailOptional: 'Correo o contacto (opcional)', problemDescription: 'Describe el problema', sendReport: 'Abrir informe por correo', reportHint: 'Esto abre tu correo con el contexto del festival incluido.', sortBars: 'Ordenar bares', numeric: 'Numérico', alphabetical: 'Alfabético', notReviewedYet: 'Aún sin estrellas', signInToSort: 'Inicia sesión para ordenar por bares sin estrellas.',
  },
} as const;

export function useFestivalLanguage() {
  const language = useState<FestivalLanguage>('festival-language', () => 'es');
  const t = (key: TranslationKey) => messages[language.value][key];
  const localized = (english?: string | null, spanish?: string | null) => language.value === 'es' ? spanish || english || '' : english || spanish || '';
  const setLanguage = (value: FestivalLanguage) => {
    language.value = value;
    if (import.meta.client) localStorage.setItem('festival-language', value);
  };

  onMounted(() => {
    const saved = localStorage.getItem('festival-language');
    if (saved === 'en' || saved === 'es') language.value = saved;
  });

  return { language, setLanguage, t, localized };
}
